name: Terraform Validate and Plan

on:
  workflow_dispatch:
  push:
    branches: 
      - main

jobs:
  validate:
    name: Terraform Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_AK}}
          aws-secret-access-key: ${{ secrets.AWS_SK }}
          aws-region: us-east-1
      - name: Terraform Validate
        run: |
          terraform init  
          terraform validate 

  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_AK}}
          aws-secret-access-key: ${{ secrets.AWS_SK }}
          aws-region: us-east-1
      - name: Initialise project and view terraform plan
        run: |
          terraform init -input=false
          terraform plan

  apply:
    name: Terraform Apply
    runs-on: ubuntu-20.04
    needs: plan
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_AK }}
          aws-secret-access-key: ${{ secrets.AWS_SK }}
          aws-region: us-east-1 
      - name: Initialise project and plan
        run: |
          terraform init -input=false
          terraform plan
      - name: Deploy terraform
        run: |
          terraform apply -auto-approve